networks:
  gitlab-net:
    name: gitlab-net

volumes:
  django-test-volume:
    name: django-test-volume

services:
  simple_app:
    image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    ports:
      - "6567:8000"
    volumes:
      - django-test-volume:/home/app/simple_app
    networks:
      - gitlab-net
